Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('singleEqType', '1', '是否為單一機台類型(非有子機台)');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('productParameter', '0', '是否有生產參數管理');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('confirmParameter', '1', '過帳時是否在畫面上確認生產參數');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('materialTracking', '0', '是否有生產耗用物料追縱');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('materialConsuming', '1', '生產物料是否自動在過帳時耗用(減量)');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('assemblyMode', '0', '是否為組裝業執行模式');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('operatorPerformance', '0', '人員效率追蹤');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('operationEqType', '1', '過帳站點可選機台。0:全部機台，1:主機台，2:子機台');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('OPIMultiInstance', '0', '是否允許一台電腦執行多個OPI');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('userLoginConstraint', '0', '用戶登入OPI限制。0:無限制，1:同時只能登入一個OPI');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('isTestEnv', '0', '是否為測試環境。0:否(正式環境)，1:是(測試環境)');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('autoLogout', '1', '15');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('LanguageUpdateDate', '1', '5/14/2014 8:32:11 PM');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('compressData', '1', '是否壓縮傳送的資料');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('parmEqTypeFlag', '1', '是否在生產規範裏顯示機台型號清單');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('productSpecSetting', '2', '生產規範ID定義。specSelectProduct = 0, productSelectSpec = 1, specEqualsToProduct = 2, specEqualsToOrder = 3');  
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('dbType', '0', 'mySql');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('simpleEqLine', '1', '是否設定機台線別。可用來控制同Line機台為優先使用機台');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('carrierManagement', '1', '是否有載具管理');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) VALUES ('carrierMaintain','0','載具維護(只有維護功能，Lot交易邏輯不會執行載具邏輯)'); 
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('componentType', '0', '是否設定生產物料類型，可設定各站點適用的生產物料。如Ingot, Brick, Wafer');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('saveCompDetailHist', '1', '是否儲存批號元件歷使清單(componentInfo=1才有作用)');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('componentInfo', '0', '是否控制批號元件(刻號)');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('lotTrackingRecord', '0', '是否啟用WIP_LOT_TRACKING記錄站點各Rule執行資訊');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('txnLocalMode', '0', '是否交易在本機端執行');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('useStepIdAsHandle', '1', '是否以StepId當成StepHandle');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('loginPrompt', '0', '是否在登出後自動彈出登入畫面');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('loginFabSelection', '0', '多廠區時是否在登入時顯示廠別讓用戶選擇');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('validateExecuteUser', '0', '是否在執行功能時再次驗證用戶密碼。0：不再次驗證,1：BRM功能, 2:MES功能, 3:所有功能');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values ('logMessageBoxLevel', '9', '記錄顯示訊息方塊內容的等級');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) VALUES ('licenseKey0','1',''); 
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE) Values  ('workFlowMonitor', '0');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values  ('multiTxnLimit','1', '10');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) Values  ('cmdTimeout','1', '5');
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) VALUES ('mergeTableCount','1','200'); 
Insert into MES_SYSTEM_CONFIG (ITEM, VALUE, VALIDATION) VALUES ('DateTimeSQL','1','select now()'); 

Insert into MES_EQP_STATE (SYSID, STATE, DESCRIPTION, AVAILABLE, COLOR, CREATE_USER, MODIFY_USER, DELETE_FLAG) Values ('ee300413-f472-46e4-96e9-6de1e7aab9d8', 'PM', '保養中', '0', -256, 'System', 'System', '0');
Insert into MES_EQP_STATE (SYSID, STATE, DESCRIPTION, AVAILABLE, COLOR, CREATE_USER, MODIFY_USER, DELETE_FLAG) Values ('c002c4b7-8e25-452f-9dab-46a2745a6872', 'IDLE', '閒置中', '1', -16744448, 'System', 'System', '0');
Insert into MES_EQP_STATE (SYSID, STATE, DESCRIPTION, AVAILABLE, COLOR, CREATE_USER, MODIFY_USER, DELETE_FLAG) Values ('80b7fb7e-46c1-414b-a7ee-693f25b768eb', 'RUN', '生產中', '1', -16776961, 'System', 'System', '0');
Insert into MES_EQP_STATE (SYSID, STATE, DESCRIPTION, AVAILABLE, COLOR, CREATE_USER, MODIFY_USER, DELETE_FLAG) Values ('b0cb1cf4-b803-44b2-9023-cfdd6c0b1c16', 'DOWN', '當機', '0', -2830136, 'System', 'System', '0');

Insert into MES_EQP_TYPE (SYSID, EQ_TYPE, DESCRIPTION, OWNER, TOOL_TYPE, CAPACITY, TRACK_COUNT, CONSUME_TYPE, COUNTER_FLAG, CREATE_USER, MODIFY_USER, DELETE_FLAG) Values ('7a05b47b-b14c-4696-b479-f5a848655715', 'virtual', '虛擬機台類別', 'System', 0, 99999, 0, 0, '0', 'System', 'System', '0');

Insert into MES_GROUP_USER_PRIVILEGE (FROM_ID, TO_ID) Values ('admin', 'a0bdac7c-b6d8-46d5-adb3-0276d0031f73');

Insert into MES_USER_PROFILE (SYSID, USER_ID, USER_NAME, DIVISION, PASSWORD, LANGUAGE, CREATE_USER, MODIFY_USER, DELETE_FLAG) Values ('a05a21d6-868c-4d7f-ad91-46e76ac64b83', 'admin', 'mes administrator', 'CIM', 'e78b7e02739672a65f6240ce33c91797', 'zh-TW', 'System', 'admin', '0');

INSERT INTO mes_lot_type (sysid,lot_type,description,check_future_hold,check_q_time,check_dc_self,check_recipe,check_dc_spec,check_material,check_tooling,create_user,create_date,modify_user,modify_date,delete_flag) VALUES ('e37a189d-e221-4dc7-9dd4-41f1c20ea81c','Production','','1','1','1','1','1','1','1','admin','2018-05-23 11:22:19','admin','2018-05-23 11:22:19','0');

INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('8c9c6f79-08e1-4341-ac70-517fd4002287', 'IDE:PARM:PARAMETER:DELETE', '生產參數刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('fd387a71-0d54-4943-8d76-e2ac550db947', 'IDE:PARM:PARAMETER:VIEW', '生產參數檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('09c0b2ba-518b-4be5-815f-6b1674f631d1', 'IDE:PARM:PARAMETER:*', '生產參數所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('a464cf19-b6e0-4287-8bc2-6dbc5619d35f', 'IDE:PARM:*', '生產規範所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('f51787e0-61d2-494a-902b-6a82f220f864', 'IDE:PARM:PARAMETER:MODIFY', '生產參數修改', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('62784256-a868-4852-b8b9-cbf91ba6a5df', 'IDE:PARM:STEPPARAMETER:*', '站點參數所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('fbadb0aa-c3c9-4422-b63b-569a4abfe208', 'IDE:PARM:STEPPARAMETER:MODIFY', '站點參數修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('ac100208-6297-4922-aeb8-85631f190408', 'IDE:PARM:STEPPARAMETER:VIEW', '站點參數檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('bbca5229-b0d3-4888-883a-aefeee2cee21', 'IDE:PARM:PRODUCTPARAMETER:VIEW', '生產規範檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('eedc7234-4eb7-4c06-98c3-c32979ea61e6', 'IDE:PARM:PRODUCTPARAMETER:*', '生產規範所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('ea4cd329-6090-4175-8bf8-af76e313706e', 'IDE:PARM:PRODUCTPARAMETER:ADD', '生產規範新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('3f97ac1d-42f6-47ba-8f5a-d475563934ae', 'IDE:PARM:PRODUCTPARAMETER:MODIFY', '生產規範修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('4ae0d5c1-9fc9-4292-afd1-a4d8c0dd9326', 'IDE:PARM:PRODUCTPARAMETER:DELETE', '生產規範刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('60e0cbca-0768-4780-9e3f-093b0efe6a7d', 'IDE:PARM:PRODUCTPARAMETER:ISSUE', '生產規範發佈功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('7d193084-32b1-4624-87c1-2f8ffaa38ffa', 'IDE:PARM:PRODUCTSPEC:*', '產品生產規範所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('d08913d3-0b78-463f-9a77-36b2fd43fba2', 'IDE:PARM:PRODUCTSPEC:ADD', '產品生產規範新增功能', 'Admin', 'Admin', '1');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('c181d560-821c-4679-adaa-fe74ba86fb12', 'IDE:PARM:PRODUCTSPEC:VIEW', '產品生產規範檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('3c760020-e1dc-4fa5-a120-1dc861895760', 'IDE:PARM:PRODUCTSPEC:MODIFY', '產品生產規範修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('d73daaa1-855d-4371-8795-2ece30e71951', 'RUN:RULE:KSR', 'KSR報表', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('8faaf97e-aa06-48e8-ab4e-beb2bc9ebd20', 'RUN:RULE:HoldLotReport', 'HoldLot報表', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e08ad2a9-a070-4478-b9b8-3fd409a962bc', 'SPC:BAS:SPCFILE:ISSUE', 'SPC檔案啟用功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('dfbbd0fc-df92-4fe3-8afa-ccb2f5ef305d', 'SPC:BAS:REASONCATEGORY:*', '原因分類所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('3774781f-8db5-432e-875a-ad510dd2975b', 'SPC:BAS:REASONCATEGORY:ADD', '原因分類新增功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('8f018f84-9fae-44f3-bea3-97a3d97c9e0b', 'SPC:BAS:REASONCATEGORY:DELETE', '原因分類刪除功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('c931c492-ff81-4c5f-ac5a-3ea2fdcfb1c7', 'SPC:BAS:REASONCATEGORY:MODIFY', '原因分類修改功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('43380d5f-8f2a-4031-a129-44ea18b4eeb8', 'SPC:BAS:REASONCATEGORY:VIEW', '原因分類檢視功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('27a63292-1bd5-42b5-a083-a8854545bd6e', 'SPC:BAS:REASONCODE:*', '原因代碼所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('fd089334-e435-4397-a1c9-fdf80ade02f9', 'SPC:BAS:REASONCODE:ADD', '原因代碼新增功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('c8fc18b5-9672-442a-81dc-913f9b522974', 'SPC:BAS:REASONCODE:DELETE', '原因代碼刪除功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e56800f4-7e62-4e0b-8a49-5dd133d28456', 'SPC:BAS:REASONCODE:MODIFY', '原因代碼修改功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('30b32063-5045-4198-89db-2262ad2a6908', 'SPC:BAS:REASONCODE:VIEW', '原因代碼檢視功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('4a93e6ac-1948-4a69-986c-429385039814', 'SPC:BAS:REASONGROUP:*', '原因代碼群組所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('bca95059-6a5c-4b92-8836-a8bc174290af', 'SPC:BAS:REASONGROUP:ADD', '原因代碼群組新增功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('40c2ade3-5c6b-42f4-b480-fd4f006899e5', 'SPC:BAS:REASONGROUP:DELETE', '原因代碼群組刪除功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('ffb9e38d-34b7-4a62-bee1-2ffed3ef8344', 'SPC:BAS:REASONGROUP:MODIFY', '原因代碼群組修改功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('25a72843-b0c1-49bd-be46-8405b447b1b7', 'SPC:BAS:REASONGROUP:VIEW', '原因代碼群組檢視功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('049542cb-f46d-44ee-8023-a30eafe9176c', 'SPC:BAS:SPEC:*', 'SPC檢驗規格所有功能', '02437', '02437', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('98fce452-5b33-45e2-8d9c-35ef640179dd', 'SPC:BAS:SPEC:ADD', 'SPC檢驗規格新增功能', '02437', '02437', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('cd277cb0-0b91-4bda-a713-96c310fb32a9', 'SPC:BAS:SPEC:MODIFY', 'SPC檢驗規格修改功能', '02437', '02437', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e61023fb-a448-48fe-a5fc-5a02de14f557', 'SPC:BAS:SPEC:DELETE', 'SPC檢驗規格刪除功能', '02437', '02437', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('22738d8a-828a-4f24-9353-fa04a56f298f', 'SPC:BAS:SPEC:VIEW', 'SPC檢驗規格檢視功能', '02437', '02437', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('6de019f4-93f5-429b-89c6-e1187e18af29', 'SPC:BAS:CONTROLTEMPLATE:*', 'SPC管控項目樣版所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('a5fa0c9f-9a62-448a-b18c-977a997ac8be', 'SPC:BAS:CONTROLTEMPLATE:ADD', 'SPC管控項目樣版新增功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('0ea77d00-d9fa-4413-b8e8-51b3b5137817', 'SPC:BAS:CONTROLTEMPLATE:MODIFY', 'SPC管控項目樣版修改功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('cbf221d0-f49d-4d1e-bef5-964af9241efb', 'SPC:BAS:CONTROLTEMPLATE:DELETE', 'SPC管控項目樣版刪除功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('91ff802b-ba44-4346-ab87-0be52a4dadde', 'SPC:BAS:CONTROLTEMPLATE:VIEW', 'SPC管控項目樣版檢視功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('cf69e553-390b-41c8-90aa-d8cf548b1196', 'RUN:RULE:EQPerformance', 'EQPerformancet報表', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('52c62767-7aa3-4649-bad8-9f885831b7ad', 'RUN:RULE:EQPAbnormal', 'EQPAbnormal報表', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e3875836-7620-4215-9243-6342bdc0e305', 'RUN:RULE:OnLineNotice', '線上即時廣播', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('c780c6c7-0d0e-4349-ba9c-b433c3eb713d', 'IDE:EQP:EQPGROUP:ROLLOUT', '執行用戶端機台清單發佈功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('58d0af14-e3ad-4a7f-911a-e5f44f6d2076', 'RUN:RULE:CancelDispatch', '取消派工', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('8a9da4f2-b125-4ea0-a894-05325b8898df', 'SPC:*', 'SPC所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('4ee6602b-d9bf-495e-9e84-63877604ac04', 'SPC:BAS:*', 'SPC基本資料設定所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('2b00a5e9-d06d-4b95-8730-162e2d2f3aa9', 'SPC:BAS:RULE:*', 'SPC檢驗規則設定所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e99fb649-35ff-4653-ac3f-7398b3788b93', 'SPC:BAS:RULE:ADD', 'SPC檢驗規則新增功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('4e1b802c-bc94-4177-a634-7b18a15f7104', 'SPC:BAS:RULE:MODIFY', 'SPC檢驗規則修改功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('03cb13ca-ed7f-4b05-bae6-cc97791be35f', 'SPC:BAS:RULE:DELETE', 'SPC檢驗規則刪除功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('89a9252f-e148-4d91-9314-afdcceb4d103', 'SPC:BAS:RULE:VIEW', 'SPC檢驗規則檢視功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('cd867149-96eb-482a-a944-8c7595b0de51', 'SPC:BAS:PROPERTY:*', 'SPC層別所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('9f6f06b1-87b5-4728-9f63-f1ae580e7a8c', 'SPC:BAS:PROPERTY:ADD', 'SPC層別新增功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('a4c94c4d-1967-4e9a-af83-bf91d8ad25da', 'SPC:BAS:PROPERTY:MODIFY', 'SPC層別修改功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('1cc84f17-417e-4172-928e-4d09e57a562e', 'SPC:BAS:PROPERTY:DELETE', 'SPC層別刪除功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('566f1146-9668-4e52-be68-c55d14592b31', 'SPC:BAS:PROPERTY:VIEW', 'SPC層別檢視功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('3f03a87b-8da7-469c-b722-ecfc2fe47503', 'SPC:BAS:SAMPLINGSTANDARD:MODIFY', 'SPC抽樣標準修改功能', 'admin', 'admin', '1');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('1adeb627-ce9c-4e5a-8889-f7213df5dc90', 'SPC:BAS:SAMPLINGSTANDARD:DELETE', 'SPC抽樣標準刪除功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('26bc8954-17c8-40e4-a44b-309d7f492a4e', 'SPC:BAS:SAMPLINGSTANDARD:VIEW', 'SPC抽樣標準檢視功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('b75f3e46-2349-49d1-ad21-2c1580e75535', 'SPC:BAS:SAMPLINGSTANDARD:*', 'SPC抽樣標準所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('5db6cf58-7ef6-479f-a3e4-98a614d91432', 'SPC:BAS:SAMPLINGSTANDARD:ADD', 'SPC抽樣標準新增功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('001f771a-defd-40e1-a067-e9dbf1dd02a0', 'IDE:USER:USERGROUP:MODIFY', '使用者群組修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('041d9e03-6179-48ad-ad94-b3b16f6a425c', 'IDE:CAR:CARRIER:MODIFY', '載具修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('05a43dfe-13c2-48ab-a0a0-eaeef0190715', 'IDE:CAT:REASONCATEGORY:VIEW', '原因分類檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('0658a80d-b8cc-42aa-8e10-df7b108a8836', 'IDE:EQP:EQPGROUP:*', '機台群組所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('096ed373-5442-4e62-ae69-7c1a7f6941f5', 'IDE:EQP:EQPGROUP:VIEW', '機台群組檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('0cfaf1a7-67a8-4baa-a74a-b673ce8ae60e', 'IDE:PRP:PRODUCT:MODIFY', '產品修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('141b30f1-07a1-45c3-9046-21e0806df53f', 'IDE:FMS:*', '設備即時監控所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('152a63c9-ff0c-4926-b2d5-3ef5ee6b68d7', 'IDE:EQP:EQPSTATECHANGE:VIEW', '狀態轉換規則檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('174109aa-e337-42cb-b03b-e98ef9f0f2ab', 'IDE:CAT:DIVISION:*', '部門所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('17b860f7-5d54-4077-981c-bbc463d8cc19', 'IDE:CAT:REASONGROUP:MODIFY', '原因代碼群組修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('17fe9042-742a-41f0-be09-4d220cca4449', 'IDE:CAT:FAB:*', '廠房所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('1985638e-a7d3-43d9-bc17-0d38bb6b8861', 'IDE:PRP:STEP:VIEW', '站點檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('19e70233-f4e1-4e4e-9afd-b77435c97398', 'IDE:EQP:EQPSTATECHANGE:*', '狀態轉換規則所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('1ae4e016-0eb8-46cd-8e2d-c1a46642e332', 'IDE:USER:ACCESSSTRING:DELETE', '權限字串刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('1d6e6397-3482-4333-b84c-84e8c9743894', 'IDE:PRP:RULE:DELETE', '站點規則刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e383be69-79ff-4122-ad42-0533ea68c057', 'IDE:CAR:CARRIER:ADD', '載具新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e6db47b7-9704-4bcf-a60e-97dac53e5433', 'IDE:PRP:STEP:DELETE', '站點刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e8291522-7825-4a90-8b30-c0ecec8572df', 'IDE:PRP:STEP:MODIFY', '站點修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e966ad4f-afb8-4016-8681-78a4b73615ea', 'IDE:CAR:CARRIER:DELETE', '載具刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e9f57943-92ef-4f58-85ec-1c4437e4c467', 'IDE:EQP:EQPSTATE:DELETE', '建立狀態刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('eabb0e3a-b71e-41e8-b390-c9c56f11a808', 'IDE:PRP:STEP:ADD', '站點新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('ead28e11-6100-4841-94d1-0060fd5fabbd', 'IDE:CAT:REASONGROUP:DELETE', '原因代碼群組刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('eb11b0d2-4544-4e52-8762-67529c354459', 'IDE:EQP:*', '機台模組所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('ec7641b0-0112-4f04-9fef-085c0784cd50', 'IDE:PRP:STEPDC:DELETE', '資料收集項目刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('efdd87a8-2fa3-43a1-8104-34b6570e9a40', 'IDE:CAT:FAB:ADD', '廠房新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('f37d0249-a64c-4ab9-9e82-b41a21e6dab3', 'IDE:EQP:EQPGROUP:DELETE', '機台群組刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('f44986f5-dcba-4a15-a466-67d13da9151f', 'IDE:USER:*', '使用者模組所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('f4c2eb42-e252-45bf-a5b9-92450eeeb68c', 'IDE:USER:USERINFO:*', '使用者資訊所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('f9f75537-3ca6-44ac-8368-ef2f57221138', 'IDE:CAT:STEPCODE:*', '檢測站代碼所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('fa634aa5-c64d-431b-8b9b-16e258c6635c', 'IDE:USER:USERINFO:VIEW', '使用者資訊檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('faff10da-a56b-42a2-bb64-95ad19ff5a05', 'IDE:PRP:PRODUCT:ISSUE', '產品啟用功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('fb464a5a-d6ae-4b6b-b964-08c0a66c4d55', 'IDE:PRP:STEPDC:ADD', '資料收集項目新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('0ccbcf05-5ebb-4fcd-966b-05cf107cef66', 'RUN:RULE:StartLot', '投料下線', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('cfdfdbe6-5037-4148-b19c-bc3903279215', 'RUN:RULE:InStepCheck', '進站', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('407fa129-e8d8-4932-81ea-bc84974027', 'IDE:CAR:CARRIER:CLEAN', '載具清潔功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('5259caa2-335c-4402-9d3c-fa72cb03d267', 'RUN:RULE:TrackIn', '進機', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('97472972-f448-4f15-92a0-3005eacce843', 'RUN:RULE:OutStepCheck', '出站', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('215a0e11-2dd4-454f-9d57-8604ea0e9291', 'RUN:AREA:FAB-A:*', '設定FAB-A所有工作區', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('49f17eb7-d36b-4834-a747-4e4db0530ef7', 'IDE:CAT:DIVISION:DELETE', '部門刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('4d38e055-68cf-4f7a-abb9-b8bc4057ff89', 'IDE:CAT:DIVISION:VIEW', '部門檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('4f4fcb43-f75b-4010-9de6-97b090bd68b4', 'IDE:CAT:REASONGROUP:ADD', '原因代碼群組新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('4f8f1025-4e36-4008-8a71-2b1f7bdcc3df', 'IDE:CAT:STEPCODE:VIEW', '檢測站代碼檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('517b18b2-d0e1-4448-8aef-e0dc5aa79167', 'IDE:USER:USERGROUP:VIEW', '使用者群組檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('5715089d-edd6-492b-b91f-142c625eb88b', 'IDE:PRP:RULE:ADD', '站點規則新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('5946d4ff-09fa-42d4-a838-75201b73e341', 'IDE:CAT:STAGE:VIEW', '大站檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('5b93b0d8-8678-4742-b453-5ebc6aa505f0', 'IDE:PRP:PRODUCT:ADD', '產品新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('5cd6d602-33e5-41d3-a3f5-54267458440c', 'IDE:CAT:REASONCODE:MODIFY', '原因代碼修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('5e59ab76-d76c-433e-b9af-b36fa965ca07', 'IDE:USER:ACCESSSTRING:MODIFY', '權限字串修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('60021ecc-7843-4552-97f2-147ccc6c9edf', 'IDE:PRP:STEP:*', '站點所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('694f703a-b13d-4115-9d34-d35b3e89da29', 'IDE:PRP:RULE:VIEW', '站點規則檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('6aed2477-3a5a-46c4-b0eb-acf6f49c7c92', 'IDE:CAR:CARTYPE:MODIFY', '載具類型修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('6e09726c-a0c2-4370-9052-0d4e642b182a', 'IDE:CAR:CARTYPE:*', '載具類型所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('6e98dc07-ff8e-4216-82b3-a196314c86aa', 'IDE:USER:USERINFO:DELETE', '使用者資訊刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('7365e5ae-cbed-4162-a918-55fd2cfb74f7', 'IDE:PRP:ROUTE:ISSUE', '流程啟用功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('743dc0ac-6c88-4c6a-be91-b868a6e8e1a6', 'IDE:CAR:CARTYPE:VIEW', '載具類型檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('748579bc-d42f-4232-957b-9200880faeb2', 'IDE:CAT:COMPONENTTYPE:VIEW', '物料類型檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('761e555a-9960-4ab3-9b4f-f85fc2b1e1b8', 'IDE:EQP:EQPEQUIPMENT:ADD', '機台新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('762e6e51-2c39-4b93-b8d6-c6a031ea2cdd', 'IDE:EQP:EQPGROUP:ADD', '機台群組新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('7765c415-52c5-4da9-ad42-5f579222e99e', 'IDE:CAT:STEPCODE:DELETE', '檢測站代碼刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('7967960c-3ac0-4b9b-a12c-b24e66ca5757', 'IDE:PRP:PRODUCT:DELETE', '產品刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('7cbd468a-1a56-4f7d-b62b-c12af089309e', 'IDE:PRP:STEP:ISSUE', '站點發佈功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('7d15fca8-2cf0-483e-bddd-9f2220499061', 'IDE:PRP:STEPDC:*', '資料收集項目所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('7de2b3cf-5cb9-4afd-88ed-4a8fcd4bd43e', 'IDE:CAT:REASONCATEGORY:ADD', '原因分類新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('7ff2621a-9927-4142-a22d-b2a723841165', 'IDE:PRP:*', '流程管理模組所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('8219bf12-8c3f-4718-83d6-67446fc360c2', 'IDE:EQP:EQPEQUIPMENT:VIEW', '機台檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('82ce4d2a-c5fc-4da8-9820-d7b9d839c44d', 'IDE:CAT:REASONCODE:DELETE', '原因代碼刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('84d75f36-f448-4745-a0ac-3a97b648492f', 'IDE:CAT:REASONCODE:VIEW', '原因代碼檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('876c2136-e373-4f63-9023-3f47ceaaefa1', 'IDE:PRP:ROUTE:VIEW', '流程檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('88ef0ad0-4841-4503-a7f4-462b60de0ede', 'IDE:PRP:ROUTE:*', '流程所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('89e85c5b-0e10-464e-ad32-041af103c0de', 'IDE:FMS:AREA:*', '設備即時監控區域設定所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('8b7d6d9d-f529-413b-85eb-f4d038899735', 'IDE:EQP:EQPTYPE:*', '機台型號所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('5757ff42-0a54-4c8b-8bd9-e844d4d69382', 'SPC:BAS:SAMPLINGRULE:*', 'SPC抽樣規則所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e7177240-7af4-43e3-b0ec-8ff064ed94bb', 'SPC:BAS:SAMPLINGRULE:ADD', 'SPC抽樣規則新增功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('ed3599c4-b3ef-4dba-b8fd-4215b880b9a6', 'SPC:BAS:SAMPLINGRULE:MODIFY', 'SPC抽樣規則修改功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('54598047-6852-4ff9-a39e-a503d3858246', 'SPC:BAS:SAMPLINGRULE:DELETE', 'SPC抽樣規則刪除功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('3ef90a77-3721-49c2-817e-2d78b3942478', 'SPC:BAS:SAMPLINGRULE:VIEW', 'SPC抽樣規則檢視功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('052b48f6-646a-4020-bc83-274a23ededc7', 'SPC:BAS:SPCFOLDER:*', 'SPC資料夾所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('90294f83-d493-428c-99db-32ba025538ab', 'SPC:BAS:SPCFOLDER:ADD', 'SPC資料夾新增功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('6fdb12bf-de18-41df-9a84-2210638ad0ae', 'SPC:BAS:SPCFOLDER:MODIFY', 'SPC資料夾修改功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e7a4f32b-af7a-4167-aa97-b71509bfd15e', 'SPC:BAS:SPCFOLDER:DELETE', 'SPC資料夾刪除功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('a451a6f0-01cc-4c6c-86b2-5ec6b46369b4', 'SPC:BAS:SPCFOLDER:VIEW', 'SPC資料夾檢視功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('bf125a25-622a-4e87-8759-83ac618fa8b12', 'IDE:CAT:ROUTETYPE:*', '流程類型所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('50c4ceb3-62e3-4153-8ad6-c466717ca9ee', 'SPC:USER:ACCESSSTRING:*', 'SPC權限字串設定所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('a6a9b19e-68f3-49e2-ab41-b845a800b83f', 'IDE:EQP:EQPEQUIPMENT:MODIFY', '機台修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('aca7c901-13a9-41fb-8704-285fe02c3bd1', 'IDE:USER:ACCESSSTRING:*', '權限字串所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('b09b328c-f969-460f-b824-180c328cd9da', 'IDE:EQP:EQPTYPE:MODIFY', '機台型號修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('b0fc2d0f-4446-444d-878f-30276842dac2', 'IDE:CAR:CARTYPE:ADD', '載具類型新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('b3bf36cb-d8c1-4b38-8fa2-3557f0684295', 'IDE:EQP:EQPEQUIPMENT:DELETE', '機台刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('b550ea43-709d-4455-be03-aaff56b1b8ea', 'IDE:PRP:PRODUCT:VIEW', '產品檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('b5d42563-110f-4ce7-8390-bf483a1a79da', 'IDE:CAT:STAGE:ADD', '大站新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('bf125a25-622a-4e87-8759-83ac618fa8b1', 'IDE:CAT:COMPONENTTYPE:*', '物料類型所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('c3c53385-4560-4138-b151-bac2283fadcc', 'IDE:USER:USERGROUP:ADD', '使用者群組新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('c8948ec3-6084-4120-b5dc-eafc14505cff', 'IDE:EQP:EQPSTATE:MODIFY', '建立狀態修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('cae3aa78-1c25-4ce6-a213-ec4c1b6c3119', 'IDE:EQP:EQPTYPE:DELETE', '機台型號刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('cb302cc5-c9e6-4068-b3eb-5d1dd5d5b91c', 'IDE:USER:ACCESSSTRING:VIEW', '權限字串檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('cb941dcc-13de-4550-bedb-6775c0747e7d', 'IDE:CAT:REASONCATEGORY:DELETE', '原因分類刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('cd1056fe-f3a3-481f-bd37-3ce4ca587260', 'IDE:EQP:EQPTYPE:ADD', '機台型號新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('d0764e94-10a6-4b7e-9759-47ec6b985ebe', 'IDE:EQP:EQPEQUIPMENT:ISSUE', '機台啟用功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('d1fe04e7-af2b-4f00-86a7-95150bb0ff48', 'IDE:FMS:AREA:VIEW', '設備即時監控區域檢視功能', 'Admin', 'Admin', '1');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('d4e0e894-025a-4281-b30c-581cad3454c0', 'IDE:PRP:STEP:STEPDC', '站點資料收集項目設定功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('d9498f6e-9c1a-4ff9-8fe1-bb7ba03bd6b5', 'IDE:EQP:EQPSTATE:*', '建立狀態所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('dda6c113-e54d-4f1f-8e42-4855b6306562', 'IDE:FMS:LAYOUT:MODIFY', '設備即時監控設備位置編輯功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('def46905-35bf-46fd-bfc8-16248923dff1', 'IDE:CAR:CARRIER:*', '載具所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e0fc3777-e876-406c-9dfa-842a010f0a1d', 'IDE:FMS:AREA:DELETE', '設備即時監控區域刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e28c7881-12bf-484c-910c-657354ee093d', 'IDE:PRP:STEPDC:MODIFY', '資料收集項目修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e2ce5aab-4eba-410a-8ef6-8f4fe1b2f167', 'IDE:EQP:EQPSTATECHANGE:ADD', '狀態轉換規則新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e3163621-e5ca-4225-b24e-f9ca7e88ab5e', 'IDE:CAT:STAGE:*', '大站所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('8e0cd917-69d7-4da0-a6f4-ac9a2a15e4bf2', 'IDE:CAT:ROUTETYPE:ADD', '流程類型新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('a44230b0-e663-4d0f-b2c7-a70f639f4ed82', 'IDE:CAT:ROUTETYPE:DELETE', '流程類型刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('748579bc-d42f-4232-957b-9200880faeb', 'IDE:CAT:ROUTETYPE:VIEW', '流程類型檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('5bc0f4bd-6948-46b9-b44b-dbe128c9c5ce', 'RUN:AREA:FAB-A:CVD:*', '設定FAB-A裏CVD大站所有站點', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('685a5388-4867-48cf-9660-90eb2e85cb31', 'RUN:CLIENT:SETTING:TOOLBAR', '設定工具列', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('510654a2-fd4a-4459-b7f4-3d446347b741', 'IDE:PRP:STEP:ROLLOUT', '執行用戶端作業區發佈', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('8af165a7-c42a-426b-a125-e1cfd60ab2fd', 'IDE:MAT:*', '耗用物料追縱模組所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('5ee7986d-5c67-4699-929a-af155caab1ee', 'IDE:MAT:MATERIALTYPE:*', '耗用物料類型所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('623d4b14-9579-4456-adc2-e96062358072', 'IDE:MAT:MATERIALTYPE:ADD', '耗用物料類型新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('ce644125-741e-4149-926c-869cee69ef4d', 'IDE:MAT:MATERIALTYPE:DELETE', '耗用物料類型刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('bfdeb0b0-39f0-47be-87a7-193157372190', 'IDE:MAT:MATERIALTYPE:VIEW', '耗用物料類型檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('aabb5e17-a0e3-4ecc-98c1-ed54e70db855', 'IDE:MAT:STEPCONSUMEMATERIAL:*', '設定站點耗用物料類型所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('124e6858-562e-40a8-82bb-31870d6b4b71', 'IDE:MAT:STEPCONSUMEMATERIAL:ADD', '站點耗用物料類型新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('0f2924dc-3bc4-4507-a46b-82851a652f0f', 'IDE:MAT:STEPCONSUMEMATERIAL:MODIFY', '站點耗用物料類型修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('2d6688d1-ad17-4c0a-a65c-5c0df96d170d', 'IDE:MAT:STEPCONSUMEMATERIAL:DELETE', '站點耗用物料類型刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('fb8b1a17-0652-48e3-86f0-14ddffe773a0', 'IDE:MAT:STEPCONSUMEMATERIAL:VIEW', '站點耗用物料類型檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('9df792af-965d-4f21-a1f6-f6115dea0f99', 'RUN:AREA:*', '設定所有工作區', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('eea70fa7-a1ee-4740-8e2a-9d2f70c8e6a9', 'RUN:RULE:ResetState', '重設機台狀態', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('edf10cc4-31f3-4b77-b163-4d60fde7692d', 'RUN:RULE:CancelTrackIn', '取消進機', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e9c9eba3-c694-42a5-8167-7c3326a63fc0', 'RUN:RULE:HoldLot', '扣押', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('51c37ac4-ddd6-4efb-95b1-6c9373208c25', 'RUN:RULE:ReleaseLot', '解扣押', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('13be8267-66d1-4658-9932-fa02940a8794', 'RUN:RULE:WorkingInstructionSet', '設定工作指示', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('5cb952d3-d329-49db-86f6-385e01a9fcaf', 'RUN:RULE:FutureHoldSet', '設定未來扣押', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('c36654de-e59f-40d2-9bb4-9b2a60212e2b', 'RUN:RULE:QTimeSet', '設定製程限時', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('ddb030ed-4f58-41b0-bbae-5e224031ca01', 'RUN:RULE:AdjustQuantity', '調整批號數量', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('d7f866fc-60d7-4464-b428-0a77c0c4f575', 'RUN:RULE:ChangeProduct', '更改產品', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('0af71a9f-da81-4150-9588-c588be1cd2d1', 'RUN:RULE:DeleteLot', '刪除批號', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('29b3250b-dce8-4afb-86eb-510f5b374dec', 'RUN:RULE:Inventory', '入庫', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('002b1474-4dd2-413a-890a-b626d484b3fd', 'RUN:RULE:LogLotHistory', '增加批號記錄', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('65a98380-838b-45d5-bf14-3d36e6b3fbf8', 'RUN:RULE:MergeLot', '併批', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('d54ab575-e458-4b9b-b09a-5cda7e65664e', 'RUN:RULE:ModifyAttribute', '修改屬性', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('90288f63-d062-4438-afa0-634e7c9cabfd', 'RUN:RULE:RepositionStep', '重新定位站點', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('078caeb4-0cd6-4900-9da5-a42a80ab9ded', 'RUN:RULE:RepositionRule', '重新定位規則', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('ab716358-9791-4009-9c2f-93ebce2bfb10', 'RUN:RULE:Rework', '重工', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('2caf9278-03d3-4a44-8105-774bffdfd9b6', 'RUN:RULE:TerminateLot', '終結批號', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('73fa7703-3f6d-40ae-adc3-54f1e965d89f', 'RUN:RULE:UnTerminateLot', '終結批號拉回', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('40105169-c7ed-42d1-800d-24cbf4af5812', 'RUN:RULE:SplitLot', '分批', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('93bd7613-cbf6-4442-8ce6-c59a6e5f427e', 'RUN:RULE:ScrapLot', '報廢', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('45b1919c-91e3-42f5-b582-e0e435eed9cd', 'RUN:RULE:UnScrapLot', '報廢拉回', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('7947ebf7-069d-497e-bcaf-29e2eae63926', 'RUN:RULE:SpecifyCarrier', '指定載具', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e46c0243-a35c-4738-9e3a-1639306306e1', 'IDE:PARM:PARAMETER:ADD', '生產參數新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('48b18fe4-3ca9-4373-83d7-8c038397cd89', 'SPC:USER:ACCESSSTRING:ADD', 'SPC權限字串設定新增功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('2ec86634-9e7f-45eb-b3db-bd31f1216496', 'SPC:USER:ACCESSSTRING:DELETE', 'SPC權限字串設定刪除功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('0512a7cf-1eac-4974-9504-b20ad813a2e2', 'SPC:USER:ACCESSSTRING:MODIFY', 'SPC權限字串設定修改功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('9d62adc0-8155-4b67-bbb9-dfde50232697', 'SPC:USER:ACCESSSTRING:VIEW', 'SPC權限字串設定檢視功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('a2f6e800-4fc4-40df-bebb-dcf050921513', 'SPC:USER:USERINFO:*', 'SPC使用者資訊所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('a1748c89-fd50-44d6-bbd0-56192687835a', 'SPC:USER:USERINFO:ADD', 'SPC使用者資訊新增功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('f215853c-9866-4707-85ba-f6835b7465e1', 'SPC:USER:USERINFO:MODIFY', 'SPC使用者資訊修改功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('4c518e1e-8e80-46f4-bc35-e15880c8988d', 'SPC:USER:USERINFO:DELETE', 'SPC使用者資訊刪除功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('51f09610-7d78-4f5b-a879-1b002813a197', 'SPC:USER:USERINFO:VIEW', 'SPC使用者資訊檢視功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('fcca1095-74ea-47f8-8bdf-b4559dcf9d15', 'SPC:USER:USERGROUP:*', 'SPC使用者群組所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('2b37a3cf-8b87-4a9c-9f8e-3d906c34727f', 'SPC:USER:USERGROUP:ADD', 'SPC使用者群組新增功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('0003eb6a-8139-4954-a53a-91b9fd2c324f', 'SPC:USER:USERGROUP:MODIFY', 'SPC使用者群組修改功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('1c4a0b6c-2cb6-4552-9359-09dab6d6a123', 'SPC:USER:USERGROUP:DELETE', 'SPC使用者群組刪除功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('efdc03f1-6d18-4d3a-9b88-a488b82698b6', 'SPC:USER:USERGROUP:VIEW', 'SPC使用者群組檢視功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e7b71d7b-083c-4cd5-83e3-5dfa0fbc2ef8', 'SPC:RUN:FILE:COLLECT:FileName', '<檔案>資料收集', 'spc', 'spc', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('4b58cd85-03ff-4f77-be02-eb77bd881eca', 'SPC:RUN:FILE:MODIFY:FileName', '<檔案>資料收集及修改', 'spc', 'spc', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('da02b2a9-c080-479e-8325-6db1e2c7d19f', 'SPC:RUN:FOLDER:COLLECT:FolderA:SubFolderA:*', '<資料夾下所有檔案>資料收集', 'spc', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('c07bfd9f-f818-4fd6-9ada-4fc1f3d8144b', 'SPC:RUN:FOLDER:MODIFY:FolderA:SubFolderA:*', '<資料夾下所有檔案>資料收集及修改', 'spc', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('327b2754-529d-4709-bd44-4415997c9556', 'SPC:RUN:FILE:COLLECT:A檔', '<檔案>資料收集', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('dbd98079-0ec6-43f9-a6eb-25f460103fc8', 'SPC:RUN:FILE:MODIFY:A檔', '<檔案>資料收集及修改', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('edec632a-2e4b-43f5-b9f1-854bfea60a26', 'SPC:RUN:FOLDER:COLLECT:FAB-B:DIF:*', '<資料夾下所有檔案>資料收集', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('44b15881-80b7-4514-a0b7-4a0a38723247', 'SPC:RUN:FOLDER:MODIFY:FAB-B:DIF:*', '<資料夾下所有檔案>資料收集及修改', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('20d7b9b1-263c-4752-a122-bf94f7317602', 'IDE:EQP:EQPTYPE:VIEW', '機台型號檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('25434620-2987-41a7-af9b-935563d745f0', 'IDE:FMS:AREA:ADD', '設備即時監控區域新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('2706d5aa-5c81-497e-989d-9bdafd5a32f7', 'IDE:PRP:STEPDC:VIEW', '資料收集項目檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('27f2cb49-5ea6-4b24-a9ce-df89ae6f3787', 'IDE:CAT:STEPCODE:ADD', '檢測站代碼新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('2b636aa6-ab8c-444b-a942-d721a38bd295', 'IDE:PRP:RULE:*', '站點規則所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('2b73e81a-bb98-4907-8f8b-cad4bc15bf30', 'IDE:EQP:EQPSTATECHANGE:DELETE', '狀態轉換規則刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('2bac9ee3-48d3-4aa6-a738-a5646b6535bc', 'IDE:CAT:DIVISION:ADD', '部門新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('2cc997e5-ebf1-40ee-a8c4-755fe80c1e64', 'IDE:PRP:PRODUCT:*', '產品所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('2dc51515-bb9a-44c6-a34f-84e42d5f7d17', 'IDE:PRP:ROUTE:DELETE', '流程刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('39898982-9366-47dd-acdd-efa082476779', 'IDE:USER:USERINFO:MODIFY', '使用者資訊修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('40133c2f-4791-47ba-8d82-e035d98be424', 'IDE:USER:USERGROUP:DELETE', '使用者群組刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('407fa129-e8d8-4932-81ea-bc8497403227', 'IDE:CAR:CARRIER:VIEW', '載具檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('418bf2ea-6b2a-4510-aa58-ae5b482af5f3', 'IDE:CAT:REASONCODE:*', '原因代碼所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('43297fa6-5171-4a7f-a5aa-f20b293502d0', 'IDE:CAT:FAB:VIEW', '廠房檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('46993110-95ab-499d-b6ff-0844b386e5fd', 'IDE:CAT:REASONCODE:ADD', '原因代碼新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('47ce7022-985c-46bd-8681-027d179756f3', 'IDE:PRP:RULE:MODIFY', '站點規則修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('49136816-8bb7-4f78-a699-794ae7e178d9', 'IDE:EQP:EQPSTATE:VIEW', '建立狀態檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('79b65ace-f6ab-4378-8204-7f337f9ce6d7', 'SPC:BAS:SPCFILE:*', 'SPC檔案所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('7d689e2f-5297-4efd-8025-691bf262d300', 'SPC:BAS:SPCFILE:ADD', 'SPC檔案新增功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('3aa20037-03eb-4f04-88d6-45bc64a8ac7b', 'SPC:BAS:SPCFILE:MODIFY', 'SPC檔案修改功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('c8475739-4caa-4afa-99bd-1b8cbbbf16c4', 'SPC:BAS:SPCFILE:DELETE', 'SPC檔案刪除功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('346ebda7-3b89-4a27-8309-c49d5eb86745', 'SPC:BAS:SPCFILE:VIEW', 'SPC檔案檢視功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('8c62b53f-8f46-4c4b-8615-65e563322225', 'IDE:USER:USERINFO:ADD', '使用者資訊新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('8d494682-faa9-4b39-9d39-02b27a7ad3a6', 'IDE:EQP:EQPEQUIPMENT:*', '機台所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('8dbbb7f4-1759-41f1-9f10-9af953b71bad', 'IDE:EQP:EQPSTATE:ADD', '建立狀態新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('8e0cd917-69d7-4da0-a6f4-ac9a2a15e4bf', 'IDE:CAT:COMPONENTTYPE:ADD', '物料類型新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('8f51fe26-6c45-4101-b76d-28ab03fa38ce', 'IDE:CAT:REASONCATEGORY:MODIFY', '原因分類修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('9359ba61-f399-4090-b0c3-d9391bc0ee9a', 'IDE:USER:ACCESSSTRING:ADD', '權限字串新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('95103728-d1e1-4786-8e06-e7c6ba8fc168', 'IDE:CAT:REASONCATEGORY:*', '原因分類所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('958ef893-cddb-4bbd-8a3d-5051803999dc', 'IDE:USER:USERGROUP:*', '使用者群組所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('97db9003-ace6-48cb-900b-5eb039a40812', 'IDE:CAT:FAB:DELETE', '廠房刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('9bdfe6d4-2ed4-4c5f-a7aa-0bc585c39a62', 'IDE:CAR:CARTYPE:DELETE', '載具類型刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('9cac841f-684d-4feb-b6fb-da61e36ea2b9', 'IDE:CAR:*', '載具模組所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('a0005c54-af8f-4e5e-a10d-daed33571f5c', 'IDE:PRP:ROUTE:MODIFY', '流程修改功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('a044d0dc-e155-412e-8742-bde829d167e3', 'IDE:CAT:REASONGROUP:VIEW', '原因代碼群組檢視功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('a0a1d376-23cb-47b4-bbd3-8f088bd08025', 'IDE:CAT:*', '基本資料維護所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('a0bdac7c-b6d8-46d5-adb3-0276d0031f73', '*', 'All Privilege', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('a30be899-ceb2-4573-99e5-4c5f8d10fc5c', 'IDE:CAT:REASONGROUP:*', '原因代碼群組所有功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('a44230b0-e663-4d0f-b2c7-a70f639f4ed8', 'IDE:CAT:COMPONENTTYPE:DELETE', '物料類型刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('a544015d-e45c-4314-8ef8-9bce4f2fa86a', 'IDE:PRP:ROUTE:ADD', '流程新增功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('a608b191-e6e2-41fc-a99d-3394acb8c305', 'IDE:CAT:STAGE:DELETE', '大站刪除功能', 'Admin', 'Admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('083b4bc3-95ef-4d49-895a-57c139010329', 'IDE:PRP:PRODUCTTYPE:*', '產品類型所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('1511d4d3-21c4-4c5a-8db7-2104d8f068fe', 'IDE:PRP:PRODUCTTYPE:ADD', '產品類型新增功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('042f81f2-3df8-40c8-ad94-717af44ebcee', 'IDE:PRP:PRODUCTTYPE:DELETE', '產品類型刪除功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('321fa267-0b72-4a98-9eb4-a2e0307be689', 'IDE:PRP:PRODUCTTYPE:VIEW', '產品類型檢視功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('1440e825-6e71-4b95-af20-f43b7a62965b', 'RUN:RUNTIME:EditTaWorkInfo', '指定當前站點作業人員', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('8771d082-2227-40db-adb9-7118c40acce3', 'RUN:RULE:EqSetupClear', '卸料', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('2c96cc30-3edf-4e09-8ac1-a25878f6c2aa', 'IDE:CAT:REASONTYPE:*', '原因歸類所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('e9c3d7a3-8aa2-4f56-8c0e-4e852d362e97', 'IDE:CAT:REASONTYPE:ADD', '原因歸類新增功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('7c85227f-de6b-445c-984c-afe21c78cf52', 'IDE:CAT:REASONTYPE:DELETE', '原因歸類刪除功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('fb29b979-b3c8-4c00-baa8-80441e0504ce', 'IDE:CAT:REASONTYPE:VIEW', '原因歸類檢視功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('ae7dbbba-8373-4a4b-966a-240288e3b841', 'IDE:LBL:LABEL:ADD', '維護標籤新增功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('228b70a1-eb60-4718-8137-5aa062dee54f', 'IDE:LBL:LABEL:MODIFY', '維護標籤修改功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('0ec2fa17-7f63-46d4-8050-8fa575ca4167', 'IDE:LBL:LABEL:DELETE', '維護標籤刪除功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('bbc7ab3d-4e0a-42c2-ad16-1401b4986e2f', 'IDE:LBL:LABEL:VIEW', '維護標籤檢視功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('c1ce0c90-b458-4316-9ee1-c10092e20cae', 'IDE:LBL:LABEL:*', '維護標籤所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('61abcd6d-f524-437b-8122-bcc88d3981a1', 'IDE:LBL:LABELTYPE:*', '維護標籤類型所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('18637407-f07a-45c9-ade6-c76dbef0d2aa', 'IDE:LBL:PRINTERMODEL:*', '維護打印機型號所有功能', 'admin', 'admin', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('9ae00ee9-4db6-4b3a-b474-ce943976e0de', 'SPC:SPCABNORMAL:*', '異常矯正措施', 'spc', 'spc', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('9af569e1-b946-4036-93f2-a0f87b615327', 'SPC:SPCABNORMAL:OCAP:*', 'OCAP所有功能', 'spc', 'spc', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('aef278e6-e4c6-4a04-81f3-28cb84b0e614', 'SPC:SPCABNORMAL:OCAP:ADD', 'OCAP新增功能', 'spc', 'spc', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('2d06b5c6-a9b3-41e7-96d6-614a06b19f94', 'SPC:SPCANALYSIS:*', '統計圖分析','spc', 'spc', '0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('6f4dea7a-a005-4a2e-bfc6-666e43e0476f', 'RUN:RULE:ChangeEquipment', '換機生產', 'admin', 'admin', '0'); 
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('43f67a15-415a-48c5-8c3b-0cd37f03c8e0', 'RUN:RULE:ClientMenu', '功能選單', 'admin', 'admin', '0');   
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('1e00d11a-85d4-4fb3-8b6d-794a691133e2','IDE:EQP:EQPARAMETER:VIEW','機台參數檢視功能','admin','admin','0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('2e992390-7818-417e-8750-ec102ae3de98','IDE:EQP:EQPARAMETER:ADD','機台參數新增功能','admin','admin','0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('62cca462-50ab-45e0-ba03-620d7611379e','IDE:EQP:EQPARAMETER:*','機台參數所有功能','admin','admin','0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('9b37610b-bcb9-46a9-ad0d-bb96dbcabf23','IDE:EQP:EQPARAMETER:MODIFY','機台參數修改功能','admin','admin','0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('c4c437ea-72d6-4a64-bc30-ace6d4193e56','IDE:EQP:EQPARAMETER:DELETE','機台參數刪除功能','admin','admin','0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('0ccc2b83-91ed-465c-869a-e34be76f469d','RUN:RULE:EqDataCollect','機台自主檢查','admin','admin','0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('1160ed99-7a25-4c29-b5c1-19c54c2a43ac','RUN:RULE:StepDataCollect','站點資料收集','admin','admin','0');
INSERT INTO MES_PRIVILEGE_STRING (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('0bc61ac0-27a8-4e69-ad7d-92673c6e5b9b','RUN:RULE:LogEqHistory','增加機台記錄','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('c826ab38-9f8c-4281-8bd7-8a1201158c4f','IDE:ALM:*','報警模組所有功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('cc2b5294-983b-44bb-a881-7721c9c50d35','IDE:ALM:ALARMLEVEL:*','報警層級所有功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('81a4782c-4c50-4f28-b543-15ceb2542b05','IDE:ALM:ALARMLEVEL:ADD','報警層級新增功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('0ce14cd0-4563-497a-ae23-298f8de4df71','IDE:ALM:ALARMLEVEL:DELETE','報警層級刪除功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('ea1197cb-0be3-4057-bc03-8b5604a748b1','IDE:ALM:ALARMLEVEL:MODIFY','報警層級修改功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('76230b6f-6001-482e-85b9-c78497fec714','IDE:ALM:ALARMREASON:*','報警原因所有功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('0cadfeb1-4bed-4bff-a0e9-ea2d6bbf8c06','IDE:ALM:ALARMREASON:ADD','報警原因新增功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('f66734a0-7201-4a72-a7ca-91d4a58c40cc','IDE:ALM:ALARMREASON:DELETE','報警原因刪除功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('c15867ae-6274-4d14-9bd4-bc0742819664','IDE:ALM:ALARMREASON:MODIFY','報警原因修改功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('6a710fba-7db1-4615-aa1e-0c7a9f3c47d4','IDE:ALM:ALARMTYPE:*','報警類型所有功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('e932882a-1b31-4ece-a456-9cdad56587d0','IDE:ALM:ALARMTYPE:ADD','報警類型新增功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('f761e609-0165-4aeb-b4bc-7f01096edd95','IDE:ALM:ALARMTYPE:DELETE','報警類型刪除功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('ac01bc66-b6cb-4411-aa81-08ebaa084f99','IDE:ALM:ALARMTYPE:MODIFY','報警類型修改功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('8715be04-78fc-4fa9-9832-b8c5fd33b591','IDE:ALM:ALARMMESSAGE:*','報警訊息所有功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('f696944a-7716-475b-9bb5-17b57b5e7fff','IDE:ALM:ALARMMESSAGE:VIEW','報警訊息檢視功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('9d50b5a4-cc09-46ab-9387-93bf41d388bb','IDE:ALM:ALARMMESSAGE:DELETE','報警訊息刪除功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('08f398ec-6dae-41f1-aa36-ab55410d2169','IDE:ALM:ALARMMESSAGE:MODIFY','報警訊息修改功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('d93520d3-7f12-4ef1-8893-524bdb8f7de6','IDE:ALM:ALARMHISTORY:VIEW','報警歷史查詢功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('80d3871c-b10c-4991-a902-415055aacfdb','IDE:USER:GRANTACCESS:VIEW','檢視受限制的賦權限字串功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) VALUES ('b9372ee0-3ad7-4b27-9df7-8e18e6aec692','IDE:USER:GRANTACCESS:MODIFY','修改受限制的賦權限字串功能','admin','admin','0');


Insert into MES_PRP_RULE (SYSID, RULE_ID, PROGRAM_CLASS, DESCRIPTION, DISPATCH_FLAG, CREATE_USER, MODIFY_USER, DELETE_FLAG) Values ('5259caa2-335c-4402-9d3c-fa72cb03d267', 'TrackIn', 'TrackIn', '進機', '0', 'System', 'System', '0');
Insert into MES_PRP_RULE (SYSID, RULE_ID, PROGRAM_CLASS, DESCRIPTION, DISPATCH_FLAG, CREATE_USER, MODIFY_USER, DELETE_FLAG) Values ('0ccbcf05-5ebb-4fcd-966b-05cf107cef66', 'TrackOut', 'TrackOut', '出機', '0', 'System', 'System', '0');
Insert into MES_PRP_RULE (SYSID, RULE_ID, PROGRAM_CLASS, DESCRIPTION, DISPATCH_FLAG, CREATE_USER, MODIFY_USER, DELETE_FLAG) Values ('cfdfdbe6-5037-4148-b19c-bc3903279215', 'InStepCheck', 'InStepCheck', '進站', '1', 'System', 'System', '0');
Insert into MES_PRP_RULE (SYSID, RULE_ID, PROGRAM_CLASS, DESCRIPTION, DISPATCH_FLAG, CREATE_USER, MODIFY_USER, DELETE_FLAG) Values ('97472972-f448-4f15-92a0-3005eacce843', 'OutStepCheck', 'OutStepCheck', '出站', '0', 'System', 'System', '0');
Insert into MES_PRP_RULE (SYSID, RULE_ID, PROGRAM_CLASS, DESCRIPTION, DISPATCH_FLAG, CREATE_USER, MODIFY_USER, DELETE_FLAG) Values ('76aab629-a2b6-448c-b40f-767c66a304ec', 'AssemblyTrackOut', 'AssemblyTrackOut', '組裝業出機功能', '0', 'admin', 'admin', '0');

/*Alarm*/
Insert into mes_alm_type (sysid,alarm_type,description,reason_group,modify_user) values ('1e9e0346-7079-4c9e-a682-4fc676de3339','EqAbnormal','機台報警','EqAbnormalReason','admin');
Insert into mes_alm_type (sysid,alarm_type,description,reason_group,modify_user) values ('503c375e-688c-416e-bf8d-6615c4932b09','EqDown','機台當機','rgChangeEqState','admin');
Insert into mes_alm_type (sysid,alarm_type,description,reason_group,modify_user) values ('79acb31c-cd20-4eff-b33b-6d28b459cd3e','LotHold','批號扣押','rgHold','admin');
Insert into mes_alm_type (sysid,alarm_type,description,reason_group,modify_user) values ('d0e3f596-a437-431e-aa15-bac35faf0001','EqParmCheck','機台參數檢查錯誤','EqParmCheckReason','admin');

/*Tooling*/
/*交易(事件)*/
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('a308c5ae-2197-4b0b-bfdb-96acd5a29c0b','-','CLEAN_OK','CLEAN','IDLE','1','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('e5fd128e-f468-487b-b666-e8036b478481','-','RELEASE','HOLD','IDLE','1','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('c7d2df96-c60d-4496-9489-adabc89b42e0','-','CLEAN','IDLE','CLEAN','1','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('98e13276-d08b-471e-998c-be05c5d1712f','-','CONSIGN_VENDOR','IDLE','IN_VENDOR','1','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('a3c0a10d-744f-4014-b17b-155ff3cd0014','-','HOLD','IDLE','HOLD','1','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('a8443348-fca7-419c-8567-798f8d2050f3','-','LEND','IDLE','SETUP','1','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('92867f7b-33cb-4ca3-96ce-fd94d15fc731','-','PM','IDLE','PM','1','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('07319178-ca33-4823-82ca-0315b0433da4','-','REPAIR','IDLE','REPAIR','1','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('03870c30-1441-48e9-8b8a-fb4d85ed698a','-','SCRAP','IDLE','SCRAP','1','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('c20e51f5-5324-49cb-b791-820d3fadc722','-','VENDOR_RETURN','IN_VENDOR','IDLE','1','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('faf4497d-a26a-4d1a-a58c-9c4bb15b16fd','-','PM_OK','PM','IDLE','1','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('7113fea9-35a6-4fb4-ae46-3a17c45eacee','-','LOT_START','READY','RUN','0','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('e114ed48-f09e-4049-a4e7-ea487290818f','-','LOT_START','RUN','RUN','0','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('2a73cd03-fb07-45e3-a26a-d45982b7e163','-','UNLOAD','READY','SETUP','0','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('d7b24493-c46e-443f-bc96-be44ddade4da','-','REPAIR_OK','REPAIR','IDLE','1','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('899dd0f9-386a-4b71-aab2-b69724f7513d','-','LOT_COMPLETE','RUN','READY','0','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('282c91b3-5d9b-4c3f-9046-71f35425f04c','-','LOT_COMPLETE','READY','READY','0','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('47f15e57-49ac-4f56-8d56-5e280fcee47f','-','UNSCRAP','SCRAP','IDLE','1','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('7c102801-4a84-4c5c-8543-273dd88d719c','-','HWSETUP','SETUP','READY','0','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('2f3b1047-9b20-4f69-8247-dd07fbb72402','-','RETURN','SETUP','IDLE','1','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('97f043e7-a2e8-474f-b1b0-9db8ffaccdb4','-','VERIFY_FAIL','VERIFY','VERIFY','1','admin','admin');
INSERT INTO mes_tol_event (sysid,type_sysid,event_name,last_status,next_status,ide_flag,create_user,modify_user) VALUES ('48afd005-3ac5-4274-865b-3bd56508b043','-','VERIFY_PASS','VERIFY','IDLE','1','admin','admin');
/*權限字串*/
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('2acf604f-3be6-4878-8fef-213e3f0fedfe','IDE:TOL:*','治工具模組所有功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('2a5b9b36-3572-47b9-b196-b50d47249e07','IDE:TOL:TOOLINGPART:DELETE','治工具料號刪除功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('2c68fb47-5322-4dc4-bc9b-babe509516d9','IDE:TOL:TOOLINGTYPE:ADD','治工具類型新增功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('34cba55d-5314-4cac-ab15-bd10b6ca3abe','IDE:TOL:TOOLINGTYPE:MODIFY','治工具類型修改功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('3ed4ffab-112c-46fb-a786-500928b6769a','IDE:TOL:TOOLINGPART:MODIFY','治工具料號修改功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('46c55daa-e768-4188-9365-c86d066367c5','IDE:TOL:TOOLINGPART:ADD','治工具料號新增功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('4f9dae61-d528-4d4d-bf19-a12a88aa4967','IDE:TOL:TOOLINGPART:*','治工具料號所有功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('c891c705-02b3-46fb-b021-d8b97d14c12a','IDE:TOL:TOOLINGTYPE:VIEW','治工具類型檢視功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('d86f7dc7-a2d0-41ea-a82a-d5288188e40b','IDE:TOL:TOOLINGPART:VIEW','治工具料號檢視功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('f02d299b-aca4-4802-b015-9069f56e0947','IDE:TOL:TOOLINGTYPE:*','治工具類型所有功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('f14c37dc-02ca-4df1-a136-ea1b3faba9f1','IDE:TOL:TOOLINGTYPE:DELETE','治工具類型刪除功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('20ed2e08-5fd1-4acd-8d75-4843ee403434','IDE:TOL:EVENT:*','治工具交易所有功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('e60dd5e4-736c-4908-8345-6c1ce7b260aa','IDE:TOL:EVENT:ADD','治工具交易新增功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('39e82df1-a5c0-4d78-b611-08ee17515591','IDE:TOL:EVENT:DELETE','治工具交易刪除功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('78ff5483-c5b1-4fac-8d46-abdcbe5f029b','IDE:TOL:EVENT:MODIFY','治工具交易修改功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('9ff57413-0601-407f-b8f1-a6a8734a54b1','IDE:TOL:EVENT:VIEW','治工具交易檢視功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('acc0b32e-e368-4b6d-af85-9b2e30df30bc','IDE:TOL:TOOLINGID:*','治工具編號所有功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('65ecf423-d634-4de4-8625-a7623fa4a092','IDE:TOL:TOOLINGID:ADD','治工具編號新增功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('f8713a18-6eea-41cc-97c4-4e36ea283a34','IDE:TOL:TOOLINGID:DELETE','治工具編號刪除功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('d63b27bd-957c-4c1b-9959-53fe15221b3e','IDE:TOL:TOOLINGID:MODIFY','治工具編號修改功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('8e58629a-a139-40a5-a6a6-5174b10fa926','IDE:TOL:TOOLINGID:VIEW','治工具編號檢視功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('a2537b99-ffaa-4407-83df-6535acffdbe0','IDE:TOL:TOOLINGID:TXN:*','治工具交易所有功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('597dc305-b4e4-4d33-a465-c419c2cce9d0','IDE:TOL:TOOLINGID:TXN:LEND','治工具交易借出功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('9fe38fbd-344d-4889-a042-7776411dfa98','IDE:TOL:TOOLINGID:TXN:SCRAP','治工具交易報廢功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('9f62f976-9afb-485e-a4a8-eff866199cf7','IDE:TOL:TOOLINGID:TXN:REPAIR','治工具交易維修功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('32549e11-eb15-4e9b-992e-42c80c267cbb','IDE:TOL:TOOLINGID:TXN:UNLOAD','治工具交易卸載功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('3c780173-33e3-48e9-93f2-a6397bf4bb86','IDE:TOL:TOOLINGID:TXN:RETURN','治工具交易歸還功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('af5c9b43-cd87-4ffe-b086-92432dc4d274','IDE:TOL:TOOLINGID:TXN:UNSCRAP','治工具交易報廢拉回功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('4ed48b02-1ab8-41fa-baa1-94267776bee5','IDE:TOL:TOOLINGID:TXN:VERIFY_PASS','治工具交易驗證(成功)功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('5fe0877b-3fac-4350-abc0-f6b7371f8a55','IDE:TOL:TOOLINGID:TXN:LOT_START','治工具交易批號開始生產功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('c15765c6-ccbf-4b05-8870-dfbb6157e803','IDE:TOL:TOOLINGID:TXN:HWSETUP','治工具交易上機功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('e0329ad2-083f-480a-a631-4c4013d102f3','IDE:TOL:TOOLINGID:TXN:LOT_COMPLETE','治工具交易批號完工功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('c20b0978-3205-429b-a63b-7c89a90634e6','IDE:TOL:TOOLINGID:TXN:PM','治工具交易保養功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('330a42cc-22dc-4937-b453-7eb4304c236d','IDE:TOL:TOOLINGID:TXN:VERIFY_FAIL','治工具交易驗證(失敗)功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('e77efb83-5f56-4142-adc5-188aae3a227a','IDE:TOL:TOOLINGID:TXN:CONSIGN_VENDOR','治工具交易托寄供應商功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('53ac5ff4-b969-40f4-8369-0ab87080a04a','IDE:TOL:TOOLINGID:TXN:CLEAN_OK','治工具交易清洗完成功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('f630f7d3-b2fe-40bc-8726-008d348e68e6','IDE:TOL:TOOLINGID:TXN:HOLD','治工具交易扣押功能','admin','admin');
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('dd877c88-60bd-4b3c-b58e-558fcec4ceff','IDE:TOL:TOOLINGID:TXN:VENDOR_RETURN','治工具交易供應商歸還功能','admin','admin');  
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('f095dec0-9ad3-421f-bd35-4ae8a7bffba8','IDE:TOL:TOOLINGID:TXN:CLEAN','治工具交易清洗功能','admin','admin'); 
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('7167dc50-0a62-4f8f-b634-a45d3eb58420','IDE:TOL:TOOLINGID:TXN:LOT_BREAK','治工具交易批號暫停生產功能','admin','admin'); 
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('afd8c712-794f-4eda-947c-124d242486d7','IDE:TOL:TOOLINGID:TXN:REPAIR_OK','治工具交易維修完成功能','admin','admin'); 
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('80ace567-7979-4bf0-aa5d-c051d8863665','IDE:TOL:TOOLINGID:TXN:RELEASE','治工具交易放行功能','admin','admin'); 
INSERT INTO mes_privilege_string (sysid,privilege_string,description,create_user,modify_user) VALUES ('51560f04-e519-4e90-a711-60d6fd686340','IDE:TOL:TOOLINGID:TXN:PM_OK','治工具交易保養完成功能','admin','admin'); 

/*Kanban*/
/*權限字串*/
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('6099b6a4-f8fc-428f-9cf2-149fd9f22573','IDE:KAN:*','看板模組所有功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('5cd96fb7-0068-4593-816c-a210741e0082','IDE:KAN:SCREEN:*','看板畫面所有功能','admin','admin','0');
Insert into mes_privilege_string (sysid,privilege_string,description,create_user,modify_user,delete_flag) values ('fd05c260-f2b7-4e9d-afcb-f92cc84653cd','IDE:KAN:CLIENT:*','看板畫面所有功能','admin','admin','0');